# Generated by Django 3.2.7 on 2021-12-26 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Grade name')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Describtion')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Grade slug')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Att_date', models.DateField(null=True, verbose_name='Date of Attendance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('exam_name', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Final', 'Final'), ('Quiz', 'Quiz')], max_length=20, null=True, verbose_name='Exam Name')),
                ('mark_value', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('full_value', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('exam_date', models.DateTimeField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'ordering': ['student', '-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date of salary')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='amount of salary')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Subject slug')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_subjects', to='listings.grade')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['grade', 'title'],
            },
        ),
    ]
