# Generated by Django 3.2.7 on 2021-12-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('listings', '0003_auto_20211226_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeattendance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_author', to='users.teacher'),
        ),
    ]
